language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - composer validate
  - static code analysis

before_install:
  - stty cols 130
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest $COMPOSER_FLAGS -vv

script: skip

jobs:
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"

    - stage: composer validate
      php: 7.1
      script:
        - composer validate
        - composer normalize --dry-run

    - stage: static code analysis
      php: 7.1
      env:  TEST=phpcs
      script: vendor/bin/phpcs --colors

    - stage: static code analysis
      php: 7.1
      env: TEST=php-cs-fixer
      script: vendor/bin/php-cs-fixer fix --dry-run -vv

    - stage: static code analysis
      php: 7.1
      env: TEST=phpstan
      script: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=768M --no-progress

notifications:
  email: false
